from typing import Protocol, List
from character import Character

class UI(Protocol):
    def show_menu(self) -> None: ...
    def print_random_character(self, c: Character) -> None: ...
    def warning_three_rows(self, rows: List[str]) -> None: ...
    def getkey(self) -> str: ...
    def clear(self) -> None: ...
    def refresh(self) -> None: ...
    def print_character_cards(self, characters: List[Character], start_y: int, start_x: int = 0) -> None: ...
    def print_top_bar(self, text: str) -> None: ...
    def print_instruction_bar(self, text: str) -> None: ...
